use not_jira;

Create Table Role (
	RoleID INTEGER AUTO_INCREMENT NOT NULL,
    RoleName VARCHAR(50),
    RoleDescription VARCHAR(100),
    CONSTRAINT PK_ROLE PRIMARY KEY (RoleID)
);

create table User (
	UserID INTEGER AUTO_INCREMENT NOT NULL,
    Username VARCHAR(15) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    FullName VARCHAR(50) NOT NULL,
    Password VARCHAR(30) NOT NULL,
    RoleID INTEGER NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY(UserID, RoleID)
);
ALTER TABLE USER ADD CONSTRAINT FK_USER_ROLE FOREIGN KEY FK_USER_ROLE (RoleID) REFERENCES ROLE (RoleID);

Create Table Priority (
	PriorityID INTEGER AUTO_INCREMENT NOT NULL,
	PriorityName VARCHAR(20), 
	PriorityDescription VARCHAR(100),
	CONSTRAINT PK_PRIORITY PRIMARY KEY (PriorityID)
);

Create Table Project (
  ProjectID INTEGER AUTO_INCREMENT NOT NULL,
  ProjectName VARCHAR(50) NOT NULL,
  Description VARCHAR(50),
  OwnerID INTEGER NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE,
  CONSTRAINT PK_PROJECT PRIMARY KEY (ProjectID, OwnerID)
);
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_OWNER FOREIGN KEY FK_PROJECT_OWNER (OwnerID) REFERENCES USER (UserID);

Create Table Issue (
  IssueID INTEGER AUTO_INCREMENT NOT NULL,
  Summary VARCHAR(50) NOT NULL,
  Description VARCHAR(50),
  Priority INTEGER NOT NULL,
  Status VARCHAR(50) NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  DueDate DATE,
  ResolutionDate TIMESTAMP,
  ReporterUserID INTEGER NOT NULL,
  AssigneeUserID INTEGER,
  ProjectID INTEGER NOT NULL,
  CONSTRAINT PK_ISSUE PRIMARY KEY (IssueID, ReporterUserID, AssigneeUserID, ProjectID, Priority)
);
ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_REPORTER_USER FOREIGN KEY FK_ISSUE_REPORTER_USER (ReporterUserID) REFERENCES USER (UserID);
ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_ASSIGNEE_USER FOREIGN KEY FK_ISSUE_ASSIGNEE_USER (AssigneeUserID) REFERENCES USER (UserID);
ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_PROJECT FOREIGN KEY FK_ISSUE_PROJECT (ProjectID) REFERENCES PROJECT (ProjectID);
ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_PRIORITY FOREIGN KEY FK_ISSUE_PRIORITY (Priority) REFERENCES PRIORITY (PriorityID);

Create Table Comment (	
  CommentID INTEGER AUTO_INCREMENT NOT NULL,
  Comment VARCHAR(50) NOT NULL,
  CommentDate TIMESTAMP NOT NULL,
  UserID INTEGER NOT NULL,
  IssueID INTEGER NOT NULL,
  CONSTRAINT PK_COMMENT PRIMARY KEY (CommentID, UserID, IssueID)
);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USER FOREIGN KEY FK_COMMENT_USER (UserID) REFERENCES USER (UserID);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_ISSUE FOREIGN KEY FK_COMMENT_ISSUE (IssueID) REFERENCES ISSUE (IssueID);

Create Table Attachment (
  AttachmentID INTEGER AUTO_INCREMENT NOT NULL,
  FileName VARCHAR(50) NOT NULL,
  FileType VARCHAR(50),
  FileSize INTEGER,
  UploadedDate TIMESTAMP,
  UserID INTEGER NOT NULL,
  IssueID INTEGER NOT NULL,
  CONSTRAINT PK_ATTACHMENT PRIMARY KEY (AttachmentID, UserID, IssueID)
);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_ATTACHMENT_USER FOREIGN KEY FK_ATTACHMENT_USER (UserID) REFERENCES USER (UserID);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_ATTACHMENT_ISSUE FOREIGN KEY FK_ATTACHMENT_ISSUE (IssueID) REFERENCES ISSUE (IssueID);

Create Table Workflow (
  WorkflowID INTEGER AUTO_INCREMENT NOT NULL,
  WorkflowName VARCHAR(50),
  Description VARCHAR(50),
  ProjectID INTEGER,
  CONSTRAINT PK_WORKFLOW PRIMARY KEY (WorkflowID, ProjectID)
);
ALTER TABLE WORKFLOW ADD CONSTRAINT FK_WORKFLOW_PROJECT FOREIGN KEY FK_WORKFLOW_PROJECT (ProjectID) REFERENCES PROJECT (ProjectID);

Create Table WorkflowStep (
  StepID INTEGER AUTO_INCREMENT NOT NULL,
  StepName VARCHAR(50) NOT NULL,
  Description VARCHAR(50),
  WorkflowID INTEGER,
  CONSTRAINT PK_WORKFLOWSTEP PRIMARY KEY (StepID, WorkflowID)
);
ALTER TABLE WORKFLOWSTEP ADD CONSTRAINT FK_STEP_WORKFLOW FOREIGN KEY FK_STEP_WORKFLOW (WorkflowID) REFERENCES WORKFLOW (WorkflowID);

Create Table WorkflowTransition (
  TransitionID INTEGER AUTO_INCREMENT NOT NULL,
  TransitionName VARCHAR(50) NOT NULL,
  Description VARCHAR(50),
  SourceStepID INTEGER,
  DestinationStepID INTEGER NOT NULL,
  WorkflowID INTEGER,
  Active BOOLEAN,
  CONSTRAINT PK_WORKFLOWTRANSITION PRIMARY KEY (TransitionID, SourceStepID, DestinationStepID, WorkflowID)
);
ALTER TABLE WORKFLOWTRANSITION ADD CONSTRAINT FK_TRANSITION_SOURCE FOREIGN KEY FK_TRANSITION_SOURCE (SourceStepID) REFERENCES WORKFLOWSTEP (StepID);
ALTER TABLE WORKFLOWTRANSITION ADD CONSTRAINT FK_TRANSITION_DESTINATION FOREIGN KEY FK_TRANSITION_DESTINATION (DestinationStepID) REFERENCES WORKFLOWSTEP (StepID);
ALTER TABLE WORKFLOWTRANSITION ADD CONSTRAINT FK_TRANSITION_WORKFLOW FOREIGN KEY FK_TRANSITION_WORKFLOW (WorkflowID) REFERENCES WORKFLOW (WorkflowID);
